name: ServerAI
main: me.jamiemac262.ServerAIReWrite.ServerAI
version: 3.4.7
description: >
             ServerAI

commands:
  warn:
    description: warn the player
  b:
    description: broadcast to the server though SAI
permissions:

    sai.admin:
        description: alerts SAI that the player is an admin, this is the only node that allow's players to update SAI
        default: false
        children:
        - sai.moderator
        - sai.gamemode
        - sai.setspawn
    sai.moderator:
        description: allow use of MOST sai functions
        default: false
        children:
        - sai.mute
        - sai.list
        - sai.kick
        - sai.ban
        - sai.tp
    sai.*:
        description: allow use of MOST sai functions
        default: false
        children:
        - sai.admin
        - sai.moderator
        - sai.gamemode
        - sai.smite 
        - sai.level
        - sai.home
        - sai.kill
    sai.cake:
        description: lets you use sai cake
        default: true
    sai.ride:
        description: lets you ride a player
        default: op
    sai.mute:
        description: allow you to mute a player
        default: op
    sai.list:
        description: allow you to list players
        default: op
    sai.gamemode:
        description: allow user to change gamemode
        default: op
    sai.kick:
        description: allow you to kick a player
        default: op
    sai.ban:
        description: allow you to ban a player
        default: op
    sai.kill:
        description: access to all commands that kill players
        default: op
    sai.level:
        description: level a player up
        default: op
    sai.tp:
        description: teleportation
        default: op
    sai.setspawn:
        description: set the spawn for SAI
        default: op
    sai.check:
        description: Check another players gamemode
        default: op
    sai.home:
        description: all commands concerning homes
        default: op